#https://www.youtube.com/watch?v=6GoEfLsTI1E&ab_channel=Geekific util
services:
  spring:
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_postgres
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - spring_network
      - spring_db_network_shared
    restart: always
    # lasat expus pentru a putea rula Postman collection-ul
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  db_postgres:
    container_name: db_postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
        - db_postgres_network
        - spring_db_network_shared
        - db_postgres_pgadmin_network_shared
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - pgadmin_network
      - db_postgres_pgadmin_network_shared
    # lasat expus pentru a vedea datele salvate in bd
    ports:
        - "${PGADMIN_EXPOSED_PORT}:${PGADMIN_PORT}"
#https://forums.docker.com/t/automatically-connect-pgadmin-to-a-postgresql-volume-on-which-there-is-a-database-and-automatically-load-a-schema-present-on-a-sql-file-with-docker-compose/124647/2
    volumes:
      - ./servers.json:/pgadmin4/servers.json
#https://forums.docker.com/t/communication-between-containers-in-different-networks/7509
#https://stackoverflow.com/questions/36035595/communicating-between-docker-containers-in-different-networks-on-the-same-host
#https://docs.docker.com/engine/network/
networks:
    spring_network:
        driver: bridge
    db_postgres_network:
        driver: bridge
    pgadmin_network:
        driver: bridge
    spring_db_network_shared:
        driver: bridge
    db_postgres_pgadmin_network_shared:
        driver: bridge

volumes:
  db_data:
