#https://www.youtube.com/watch?v=6GoEfLsTI1E&ab_channel=Geekific util
#adaugarea de restat:always?
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres